export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST';
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS';
export const SINGLE_PRODUCT_FAILURE = 'SINGLE_PRODUCT_FAILURE';

export const ADDTO_CART_REQUEST = 'ADDTO_CART_REQUEST';
export const ADDTO_CART_SUCCESS = 'ADDTO_CART_SUCCESS';
export const ADDTO_CART_FAILURE = 'ADDTO_CART_FAILURE';

export const INCREASE_QTY = 'INCREASE_QTY';
export const DECREASE_QTY = 'DECREASE_QTY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
